export default [
    {    
      name: 'Jumprope',
      duration: 180,
      planeOfMotion: 'sagittal',
      writtenInstructions: `The trick here is all in the wrist. You shouldn't be moving your wrists, rather rotating them circularly`,
      mediaInstructions: 'https://www.youtube.com/watch?v=fLiozP7GVeA',
      spaceNeeded: 'smallCorner',
      cardioIntensity: 'low',
      impactToBody: 'low',
      equipmentNeeded: 'jumprope',
  },
  {    
      name: 'Jumping Jacks',
      duration: 60,
      planeOfMotion: 'frontal',
      writtenInstructions: `Try to be explosive in how you go into the X Shape`,
      mediaInstructions: 'https://www.youtube.com/watch?v=UpH7rm0cYbM',
      spaceNeeded: 'smallCorner',
      cardioIntensity: 'low',
      impactToBody: 'low',
      equipmentNeeded: '',
  },
  {    
      name: 'Lateral Steps',
      duration: 60,
      planeOfMotion: 'frontal',
      writtenInstructions: `Land softly and explode off the step`,
      mediaInstructions: 'https://www.youtube.com/watch?v=UpH7rm0cYbM',
      spaceNeeded: 'smallCorner',
      cardioIntensity: 'low',
      impactToBody: 'low',
      equipmentNeeded: '',
  },
      {
        name: 'Monkey Bars',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: `It's a motion similar to jumping jacks, but imagine you're swinging on the monkey bars - some people liken this to swimming, as well`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Squat Jacks',
        duration: 60,
        planeOfMotion: 'frontal',
        writtenInstructions: 'Like a jumping jack, but at the end of motion squat and hop back in',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: ''
      },
      {
        name: 'High Knee to Elbow Twist',
        duration: 60,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'Bring one knee up like a high knee, take the opposite elbow and rotate down to touch the knee',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Butt Kickers',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Bring your feet to your glutes',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Skiers',
        duration: 60,
        planeOfMotion: 'frontal',
        writtenInstructions: 'Hop from side to side, try to load up on the leg you land on and explode out',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'High Knees',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Make sure your knees are coming up to the bottom of your chest',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'Squat Jumps',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Explode into the jump',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'Runs',
        duration: 90,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Run back and forth 3 times',
        mediaInstructions: 'google.com',
        spaceNeeded: 'openField',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Push ups',
        duration: 30,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Just do it',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Reverse Burpee to High Knees',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: '10 high knees and then burpee',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'Reverse Burpee to Jump Squat',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Jump Squat and then burpee',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'Reverse Burpee to Jumping Knee Tuck',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Jumping Knee Tuck (get the knee to the chest) and then burpee',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'Goblet Squat to High Knee',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Slow single knee up on each side after the goblet squat',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'kettlebell'
      },
      {
        name: 'Curl and Press',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Bicep Curl to Overhead Press',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Band Rows',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Get the shoulder blades down and back and then pull and be able to squeeze a pencil with your lats',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: 'band'
      },
      {
        name: 'Suicide Burpees',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Run one way, burpee, run back burpee that's 1. Do that 10 times.',
        mediaInstructions: 'google.com',
        spaceNeeded: 'openField',
        cardioIntensity: 'high',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Bear Crawls',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Keep your back straight and knees just 1-2 inches off the ground.',
        mediaInstructions: 'google.com',
        spaceNeeded: 'openField',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: ''
      },
      {
        name: 'Reverse Lunges',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Take a big step back and then drive that knee to the ground, drive back up using your hips and glutes',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Squat Gap Jump Burpees',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: `Squat down, jump like you're jumping from one cliff to another and come down into a burpee`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'openField',
        cardioIntensity: 'high',
        impactToBody: 'high',
        equipmentNeeded: ''
      },
      {
        name: 'DB Row',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'Shoulder down and back, keep the elbow close to the body almost grazing the body on the way up, slow control on the way down',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Prisoner Lunge with Twist',
        duration: 60,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'Hands behind your head',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'T Push up',
        duration: 45,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'You should look like a Jesus on the cross at the top of this motion',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Band Pull Apart',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'shoulders down and back',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: 'band'
      },
      {
        name: 'Rotator Cuff Extension',
        duration: 60,
        planeOfMotion: 'frontal',
        writtenInstructions: 'slow control motion',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: 'band'
      },
      {
        name: 'Frontal Cuff Extension',
        duration: 60,
        planeOfMotion: 'frontal',
        writtenInstructions: 'focus on eccentric control more than contraction',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: 'band'
      },
      {
        name: 'Spiderman Push ups',
        duration: 45,
        planeOfMotion: 'sagittal, frontal',
        writtenInstructions: 'knee should touch elbow',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: ''
      },
      {
        name: 'Rotating Shoulder Press',
        duration: 60,
        planeOfMotion: 'frontal, transverse',
        writtenInstructions: 'slight pivot on the feet',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'KB Swing',
        duration: 45,
        planeOfMotion: 'sagittal',
        writtenInstructions: `go back like you're holding groceries and trying to close the car door with your butt, drive up with your hips`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'low',
        equipmentNeeded: 'kettlebell'
      },
      {
        name: 'Cross Body Row',
        duration: 60,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'watch youtube video of this',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'band'
      },
      {
        name: 'Goblet Squat',
        duration: 45,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'breathe all the air in your stomach out at the top of this motion',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'kettlebell'
      },
      {
        name: 'Hammer Curl',
        duration: 45,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'make sure to come all the way down',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Straight Arm Pulldowns',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'shoulders down and back',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: 'band'
      },
      {
        name: 'Glute Bridge with Chest Press',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'use a resistance band for extra tension',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'low',
        equipmentNeeded: ''
      },
      {
        name: 'Squat to Band Pull',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'breathing in key here',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'low',
        impactToBody: 'medium',
        equipmentNeeded: 'band'
      },
      {
        name: 'Plank Shoulder Tap and Arm Extension',
        duration: 60,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'slow and steady',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: ''
      },
      {
        name: 'Chest Fly Leg Raise',
        duration: 60,
        planeOfMotion: 'frontal, sagittal',
        writtenInstructions: `legs shouldn't touch the ground`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Tricep Kick Glute Bridge into Power up',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'use a 2 or 3 pound weight, even 2 waterbottles',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Power up',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'drive your knees up and you come up with your upper body',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'Windshield Wipers',
        duration: 60,
        planeOfMotion: 'sagittal, transverse',
        writtenInstructions: 'get the knees to touch the dumbbells',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'DB Rotation',
        duration: 60,
        planeOfMotion: 'transverse',
        writtenInstructions: `like you're throwing a hook`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'DB Leg Raise',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'slow control motion',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'DB Knee Tuck',
        duration: 60,
        planeOfMotion: 'sagittal',
        writtenInstructions: 'slow control motion',
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      },
      {
        name: 'DB Russian Twist',
        duration: 60,
        planeOfMotion: 'transverse',
        writtenInstructions: `like you're trying to get the nipple outside of the opposite knee`,
        mediaInstructions: 'google.com',
        spaceNeeded: 'smallCorner',
        cardioIntensity: 'medium',
        impactToBody: 'medium',
        equipmentNeeded: 'dumbbell'
      }
    ]